'use client';

import { useEffect, useState } from 'react';
import DOMPurify from 'dompurify';
import { Card, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { Modal, ModalFooter } from '@/components/ui/Modal';
import { lettersApi } from '@/lib/api';
import { cn } from '@/lib/utils';
import { RefreshCw, FileText, Download, Eye } from 'lucide-react';
import type { LetterGenerated } from '@/types';
import toast from 'react-hot-toast';

const letterTypeColors: Record<string, string> = {
  OFFER_LETTER: 'success',
  APPOINTMENT_LETTER: 'info',
  INCREMENT_LETTER: 'success',
  CONFIRMATION_LETTER: 'info',
  RELIEVING_LETTER: 'warning',
  EXPERIENCE_LETTER: 'info',
  TRANSFER_LETTER: 'gray',
  PROMOTION_LETTER: 'success',
  WARNING_LETTER: 'warning',
  TERMINATION_LETTER: 'danger',
  OTHER: 'gray',
};

export default function MyLettersPage() {
  const [letters, setLetters] = useState<LetterGenerated[]>([]);
  const [loading, setLoading] = useState(true);
  const [previewModalOpen, setPreviewModalOpen] = useState(false);
  const [previewLetter, setPreviewLetter] = useState<LetterGenerated | null>(null);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    setLoading(true);
    try {
      const res = await lettersApi.getMyLetters();
      setLetters(res.data);
    } catch (error) {
      console.error('Failed to load letters:', error);
      toast.error('Failed to load letters');
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPdf = async (letter: LetterGenerated) => {
    try {
      const typeName = letter.template?.type?.replace(/_/g, '-').toLowerCase() || 'letter';
      await lettersApi.downloadPdf(letter.id, `${typeName}.pdf`);
    } catch (error) {
      console.error('Failed to download PDF:', error);
      toast.error('Failed to download PDF');
    }
  };

  const openPreview = async (letter: LetterGenerated) => {
    try {
      const res = await lettersApi.getGeneratedById(letter.id);
      setPreviewLetter(res.data);
      setPreviewModalOpen(true);
    } catch {
      toast.error('Failed to load letter');
    }
  };

  const formatDate = (dateStr: string) =>
    new Date(dateStr).toLocaleDateString('en-IN', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
    });

  const sanitizeHtml = (html: string) => DOMPurify.sanitize(html);

  return (
    <>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-warm-900 flex items-center gap-2">
              <FileText className="w-7 h-7 text-primary-600" />
              My Letters
            </h1>
            <p className="text-warm-600 mt-1">
              View and download your official letters
            </p>
          </div>
          <Button variant="secondary" onClick={loadData} disabled={loading}>
            <RefreshCw className={cn('w-4 h-4 mr-2', loading && 'animate-spin')} />
            Refresh
          </Button>
        </div>

        {/* Content */}
        {loading ? (
          <div className="flex items-center justify-center py-20">
            <div className="h-12 w-12 animate-spin rounded-full border-4 border-primary-600 border-t-transparent" />
          </div>
        ) : letters.length === 0 ? (
          <Card>
            <CardContent className="py-16 text-center">
              <FileText className="w-16 h-16 text-warm-300 mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-warm-900 mb-2">No Letters Yet</h3>
              <p className="text-warm-600">
                Your official letters will appear here once they are generated by HR.
              </p>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-4">
            {letters.map((letter) => (
              <Card key={letter.id}>
                <CardContent className="py-4">
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <h3 className="text-base font-semibold text-warm-900">
                          {letter.template?.name || 'Letter'}
                        </h3>
                        {letter.template && (
                          <Badge variant={letterTypeColors[letter.template.type] as 'success' | 'info' | 'warning' | 'danger' | 'gray'}>
                            {letter.template.type.replace(/_/g, ' ')}
                          </Badge>
                        )}
                      </div>
                      <div className="flex items-center gap-4 mt-2 text-xs text-warm-400">
                        <span>Issued {formatDate(letter.generatedAt)}</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-1 flex-shrink-0">
                      <button
                        onClick={() => openPreview(letter)}
                        className="p-2 text-warm-400 hover:text-warm-600 hover:bg-warm-100 rounded-lg transition-colors"
                        title="Preview"
                      >
                        <Eye className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleDownloadPdf(letter)}
                        className="p-2 text-warm-400 hover:text-primary-600 hover:bg-primary-50 rounded-lg transition-colors"
                        title="Download PDF"
                      >
                        <Download className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>

      {/* Preview Modal */}
      <Modal
        isOpen={previewModalOpen}
        onClose={() => setPreviewModalOpen(false)}
        title={previewLetter?.template?.name || 'Letter Preview'}
        size="lg"
      >
        {previewLetter && (
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-sm text-warm-500">
              <Badge variant={letterTypeColors[previewLetter.template?.type || 'OTHER'] as 'success' | 'info' | 'warning' | 'danger' | 'gray'}>
                {previewLetter.template?.type.replace(/_/g, ' ')}
              </Badge>
              <span>· Issued {formatDate(previewLetter.generatedAt)}</span>
            </div>
            <div
              className="prose prose-sm max-w-none p-4 bg-warm-50 rounded-lg border border-warm-200"
              dangerouslySetInnerHTML={{ __html: sanitizeHtml(previewLetter.content) }}
            />
          </div>
        )}
        <ModalFooter>
          <Button variant="secondary" onClick={() => setPreviewModalOpen(false)}>
            Close
          </Button>
          {previewLetter && (
            <Button onClick={() => handleDownloadPdf(previewLetter)}>
              <Download className="w-4 h-4 mr-2" />
              Download PDF
            </Button>
          )}
        </ModalFooter>
      </Modal>
    </>
  );
}
